version: "3.8"
services:
  some-redis:
    image: redis:latest
    ports:
      - 6379:6379

  gohomecontainer:
    image: gohome:latest
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - REDISURI=some-redis:6379
    depends_on:
      - some-redis